[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
delegate_vault = "AHNJKkm4Gd3FpUrdhYsuvf7tPErUpR8dgmx6xNPSHNuc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
idl-init = "anchor idl init -f ./target/idl/delegate-vault.json 8KQG1MYXru73rqobftpFjD3hBD8Ab3jaag8wbjZG63sx --provider.wallet ~/.config/solana/id.json --provider.cluster SET_RPC_HERE"
