[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
delegate_vault = "frnxh6RXdbpvTbhQ8yRtEbLNnXKmbGEqwfwMpZaBRw9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy-mainnet = "solana program deploy target/deploy/delegate_vault.so --program-id target/deploy/delegate_vault-keypair.json -C ~/.config/solana/cli/config.yml --use-rpc --with-compute-unit-price 10"
write-buffer = "solana program write-buffer ./target/deploy/delegate_vault.so -C ~/.config/solana/cli/config.yml --use-rpc --with-compute-unit-price 10"
extend = "solana program extend frnxh6RXdbpvTbhQ8yRtEbLNnXKmbGEqwfwMpZaBRw9 200000 -C ~/.config/solana/cli/config.yml -k ~/.config/solana/id.json"
idl-init = "anchor idl init -f target/idl/delegate_vault.json frnxh6RXdbpvTbhQ8yRtEbLNnXKmbGEqwfwMpZaBRw9 --provider.wallet ~/.config/solana/id.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/index.ts"
